from marketinsights.connectors.Connector import Connector
from marketinsights.connectors.OHLCFileParser import OHLCFileParser
from marketinsights.connectors.YahooConnector import YahooConnector
from marketinsights.connectors.IGConnector import IGConnector
from marketinsights.connectors.BarChartConnector import BarChartConnector
from marketinsights.connectors.MDSConnector import MDSConnector
from marketinsights.connectors.PickleConnector import PickleConnector
from marketinsights.connectors.MemoryConnector import MemoryConnector
